### ISSUE TITLE
Turbulent ONERA M6

### ISSUE THREAD

**Issue by malteyp** [su2code/Tutorials#1]
Hi,

I ran the case Turbulent Onera M6 with the configuration file ("turb_ONERAM6.cfg") and the mesh ("mesh_ONERAM6_turb_hexa_43008.su2") and SU2 v.7.

Before doing my own simulations, I wanted to check in a first step the Cp on the slices (at 20%, 65%, 80%, and 95%) of this tutorial by post-treating the result with Paraview.
However, I didn't get the same results as in the tutorial (my curves are a little bit smoother).

May  you precise in the tutorial how you made the post-treatment ?

Sincerely,

Pierre

Link : https://su2code.github.io/tutorials/Turbulent_ONERAM6/

**Comment by pcarruscag** [comment]
Hi,
I'm sorry no one replied, this repo is not tracked by most of us, there is usually more movement on CFD-Online for this type of issue.
The solver may also have changed a bit since the tutorial was created.
